# fly.toml app configuration file generated for discord-aladin on 2024-01-06T16:21:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-aladin"
primary_region = "nrt"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
size = "shared-cpu-1x"
cpus = 1
cpu_kind="shared"
memory_mb = 256
